routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\IndoregionController;
use App\Http\Controllers\QueryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::middleware(['auth'])->group(function(){
    Route::redirect('/', '/articles');
    Route::get('/query', [QueryController::class, 'index'])->name('query.index');
    Route::get('/table', [QueryController::class, 'table'])->name('table');
    Route::get('/dependent', [IndoregionController::class, 'region'])->name('dependent');
    Route::post('/regencies', [IndoregionController::class, 'getRegencies'])->name('regencies');
    Route::post('/districts', [IndoregionController::class, 'getDistricts'])->name('districts');
    Route::post('/villages', [IndoregionController::class, 'getVillages'])->name('villages');
    Route::controller(CommentController::class)->group(function () {
        Route::post("comments/{article}", "store")->name("comments.store");
        Route::delete("comments/{comment}", "destroy")->name("comments.delete");
    });
    Route::resource('articles', ArticleController::class);

    Route::post("/logout", function () {
        Auth::logout();
        return redirect()->route("login");
    })->name("logout");
});

// login
Route::middleware('guest')->group(function () {
    Route::get('/register', [AuthController::class , 'formRegister'])->name('register');
    Route::post('/register', [AuthController::class , 'formRegisterProcess']);
    Route::get('/login', [AuthController::class , 'formLogin'])->name('login');
    Route::post('/login', [AuthController::class , 'formLoginProcess']);
});

resources/views/includes/meta.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>App</title>

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-body">
    <div class="container">
        <a class="navbar-brand text-white font-lora d-md-none" href="{{ url('/') }}">App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex flex-md-row flex-column justify-content-between w-100">
                <a class="navbar-brand text-white font-lora d-none d-md-block" href="{{ url('/') }}">App</a>
                <ul class="navbar-nav mb-2 mb-lg-0 order-sm-last">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white text-capitalize" href="javascript:void(0)"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ auth()->user()->name }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg-end">
                            <li>
                                <a class="dropdown-item" href="{{ route('articles.create') }}">Buat Article</a>
                            </li>
                            <hr class="dropdown-divider">
                            <li>
                                <a class="dropdown-item" href="#">My Article</a>
                            </li>
                            <li>
                                <form action="{{ route('logout') }}" method="post">
                                    @csrf
                                    <a class="dropdown-item"
                                        onclick="event.preventDefault();this.closest('form').submit();"
                                        href="javascript:void(0)">Logout</a>
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ Route::is('articles*') ? 'active' : '' }}" aria-current="page"
                            href="{{ route('articles.index') }}">OOP</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ request()->routeIs('dependent') ? 'active' : '' }}"
                            href="{{ route('dependent') }}">Dependent Dropdown</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link
                        {{ request()->routeIs('query.index') ? 'active' : '' }}"
                            aria-current="page" href="{{ route('query.index') }}">Optimasi
                            Query</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Charts</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/includes/script.blade.php
<input type="hidden" id="table-url" value="{{ route('table') }}">
{{-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script> --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
</script>
<script src="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.js"></script>
<script src="{{ asset('main.js') }}"></script>

resources/views/includes/style.blade.php
<!-- Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
<link
    href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,500;0,600;1,500&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;1,300&display=swap"
    rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link href="https://cdn.datatables.net/v/bs5/dt-1.13.6/datatables.min.css" rel="stylesheet">
<style>
    body {
        font-family: 'Poppins', sans-serif;
    }

    ::-webkit-scrollbar {
        width: 7px;
        height: 7px;
    }

    ::-webkit-scrollbar-track {
        box-shadow: inset 0 0 3px rgba(0 0 0 / 0.15);
    }

    ::-webkit-scrollbar-thumb {
        background: linear-gradient(125deg, #f5f5f5, #ddd);
        border-radius: 10px;
    }

    .font-lora {
        font-family: 'Lora', serif;
    }

    .line-clamp {
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 1;
        overflow: hidden;
    }

    .line-clamp-3 {
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3;
        overflow: hidden;
    }
</style>