routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\IndoregionController;
use App\Http\Controllers\QueryController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::middleware(['auth'])->group(function(){
    Route::redirect('/', '/articles');
    Route::get('/query', [QueryController::class, 'index'])->name('query.index');
    Route::get('/table', [QueryController::class, 'table'])->name('table');
    Route::get('/dependent', [IndoregionController::class, 'region'])->name('dependent');
    Route::post('/regencies', [IndoregionController::class, 'getRegencies'])->name('regencies');
    Route::post('/districts', [IndoregionController::class, 'getDistricts'])->name('districts');
    Route::post('/villages', [IndoregionController::class, 'getVillages'])->name('villages');
    Route::controller(CommentController::class)->group(function () {
        Route::post("comments/{article}", "store")->name("comments.store");
        Route::delete("comments/{comment}", "destroy")->name("comments.delete");
    });
    Route::resource('articles', ArticleController::class);

    Route::post("/logout", function () {
        Auth::logout();
        return redirect()->route("login");
    })->name("logout");
});

// login
Route::middleware('guest')->group(function () {
    Route::get('/register', [AuthController::class , 'formRegister'])->name('register');
    Route::post('/register', [AuthController::class , 'formRegisterProcess']);
    Route::get('/login', [AuthController::class , 'formLogin'])->name('login');
    Route::post('/login', [AuthController::class , 'formLoginProcess']);
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $with = ['category', 'user'];
    protected $casts = [
        'published_at' => 'datetime',
    ];

    public function getFullInfoAttribute()
    {
        return $this->title . ' created by ' . $this->author;
    }

    // Metode khusus untuk mendapatkan informasi posting blog
    public function getBlogInfoAttribute()
    {
        return $this->getFullInfoAttribute() . ', Category: ' . $this->category->name;
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault([
            'name' => 'Guest Author',
        ]);
        // withDefault() = jika user tidak ditemukan, maka akan mengembalikan nilai default
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        // return $this->hasMany(Comment::class);
        return $this->morphMany(Comment::class, 'commentable');
        // morphMany() = untuk mengambil semua komentar yang berkaitan dengan artikel
        // kenapa morphMany() kenapa tidak hasMany()?
        // karena kita menggunakan polymorphic relationship untuk menghubungkan model Comment dengan model Article dan model User (Commentable)
        // berarti commentable_type dan commentable_id karna kita menggunakan morphMany() kah?
        // ya, karena kita menggunakan morphMany() maka kita harus menambahkan commentable_type dan commentable_id pada model Comment
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;
use App\Models\Comment;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('articles.index', [
            'articles' => Article::latest()->paginate(10),
            'secArticle' => Article::latest()->limit(2)->get(),
            'inheArticle' => Article::latest()->limit(2)->get(),
            'commArticle' => Article::latest()->limit(2)->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Article $article)
    {
        return view('articles.create',[
            'categories' => Category::select("id", "name")->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $data['user_id'] = auth()->id();
        $data['category_id'] = $request->category_id;
        $data['slug'] = str($request->title . '-' . str()->random(5))->slug();
        $data['published_at'] = now();
        Article::create($data);
        return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Article $article)
    {
        $comments = Comment::query()
            ->select("user_id", "body", "created_at", "id")
            ->with("user")
            ->whereMorphedTo("commentable", $article)
            // whereMorphedTo() = mencari comment yang memiliki commentable_type = App\Models\Article dan commentable_id = $article->id
            ->get();
        return view('articles.show', [
            'article' => $article->load('category'),
            'comments' => $comments,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Article $article)
    {
        return view('articles.edit', [
            'article' => $article,
            'categories' => Category::select("id", "name")->get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Article $article)
    {
        $data = $request->all();
        $data['category_id'] = $request->category_id;
        $data['slug'] = str($request->title . '-' . str()->random(5))->slug();
        $data['status'] = $request->status;
        $article->update($data);
        return redirect()->route('articles.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return back();
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content -->
    <section class="p-4">
        <div class="container">
            <h4 class="text-center font-lora">
                <a class="text-decoration-none text-dark" href="{{ route('articles.index') }}">
                    <svg class="me-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
                    </svg>
                </a>
                Create Article
            </h4>
            <div class="mt-4 gap-4 d-flex justify-content-center">
                <div class="card col-4">
                    <div class="card-body">
                        <form action="{{ route('articles.store') }}" method="post">
                            @csrf
                            <div class="mb-3">
                                <label for="name" class="form-label">Title</label>
                                <input type="text" name="title" placeholder="Title" class="form-control"
                                    id="name">
                            </div>
                            <div class="mb-3">
                                <label for="name" class="form-label">Author</label>
                                <input type="text" name="author" placeholder="Name" value="{{ auth()->user()->name }}"
                                    class="form-control" id="name">
                            </div>
                            <div class="mb-3">
                                <label for="desa" class="form-label">Categories</label>
                                <select class="form-select" name="category_id" id="desa"
                                    aria-label="Default select example">
                                    <option selected>-- Pilih Category --</option>
                                    @foreach ($categories as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="name" class="form-label">Desc</label>
                                <textarea name="description" id="desc" cols="20" rows="10" class="form-control" placeholder="Desc..."></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content -->
    <section class="p-4">
        <div class="container">
            <h4 class="text-center font-lora">
                <a class="text-decoration-none text-dark" href="{{ route('articles.index') }}">
                    <svg class="me-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
                    </svg>
                </a>
                Edit Article {{ $article->title }}
            </h4>
            <div class="mt-4 gap-4 d-flex justify-content-center">
                <div class="card col-4">
                    <div class="card-body">
                        <form action="{{ route('articles.update', $article) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="mb-3">
                                <label for="name" class="form-label">Title</label>
                                <input type="text" name="title" value="{{ $article->title }}" placeholder="Title"
                                    class="form-control" id="name">
                            </div>
                            <div class="mb-3">
                                <label for="name" class="form-label">Author</label>
                                <input type="text" name="author" value="{{ $article->author }}" placeholder="Name"
                                    value="{{ auth()->user()->name }}" class="form-control" id="name">
                            </div>
                            <div class="mb-3">
                                <label for="desa" class="form-label">Categories</label>
                                <select class="form-select" name="category_id" id="desa"
                                    aria-label="Default select example">
                                    @foreach ($categories as $item)
                                        <option value="{{ $item->id }}"
                                            {{ $article->category_id == $item->id ? 'selected' : '' }}>{{ $item->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="desa" class="form-label">Status</label>
                                <div class="d-flex flex-column gap-2">
                                    <div>
                                        <input type="radio" name="status" id="pending" value="pending"
                                            {{ $article->status == 'pending' ? 'checked' : '' }}>
                                        <label for="pending">Pending</label>
                                    </div>
                                    <div>
                                        <input type="radio" name="status" id="published" value="published"
                                            {{ $article->status == 'published' ? 'checked' : '' }}>
                                        <label for="published">Published</label>
                                    </div>
                                    <div>
                                        <input type="radio" name="status" id="draft" value="draft"
                                            {{ $article->status == 'draft' ? 'checked' : '' }}>
                                        <label for="draft">Draft</label>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="name" class="form-label">Desc</label>
                                <textarea name="description" id="desc" cols="20" rows="10" class="form-control" placeholder="Desc...">
                                    {{ $article->description }}
                                </textarea>
                            </div>
                            <button type="submit" class="btn btn-warning">Edit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="p-3 mt-4">
            <h5 class="text-center mb-4">
                OOP (Pemrograman Berorientasi Objek)
            </h5>
            <p>
                <b>Object-Oriented Programming</b>, adalah paradigma pemrograman yang menggunakan konsep objek untuk
                mendesain dan
                mengorganisir kode. Objek dalam konteks ini adalah instansiasi dari kelas, yang merupakan blueprint atau
                template untuk objek. Setiap objek dapat memiliki atribut (variabel) dan metode (fungsi) yang terkait
                dengannya. Konsep utama dalam OOP melibatkan empat pilar:
            </p>
            <p>
                Di bawah ini aku akan memberikan contoh penerapan konsep OOP dalam Laravel dengan menggunakan contoh
                sederhana. Sebagai contoh, kita akan membuat artikel atau blog sederhana dengan beberapa kolom: Title,
                Author, dan Published at, Status dan ada juga Category dari table Categories yang foreign idnya ada di table
                Articles begitupun untuk Author. Kami akan menggunakan Eloquent, ORM (Object-Relational Mapping) di Laravel,
                untuk
                menghubungkan model dengan tabel dalam database.
            </p>
            <span class="fw-bold">Table Artikel</span>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="text-center" scope="col">No</th>
                            <th scope="col">Title</th>
                            <th scope="col">Author</th>
                            <th class="text-center" scope="col">Category</th>
                            <th class="text-center" scope="col">Status</th>
                            <th class="text-center" scope="col">Publish</th>
                            <th class="text-center" scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($articles as $item)
                            <tr>
                                <th class="text-center" scope="row">{{ $loop->iteration }}</th>
                                <td>{{ $item->title }}</td>
                                <td>{{ $item->user->name }}</td>
                                <td class="text-center">{{ $item->category->name }}</td>
                                <td class="text-center">
                                    <span
                                        class="badge {{ $item->status == 'pending' ? 'bg-warning' : ($item->status == 'published' ? 'bg-success' : 'bg-secondary') }}">{{ $item->status }}</span>
                                </td>
                                <td class="text-center">{{ $item->published_at->format('d/m/y') }}</td>
                                <td class="text-center">
                                    <a href="{{ route('articles.edit', $item) }}" class="btn btn-sm btn-warning">Edit</a>
                                    <form action="{{ route('articles.destroy', $item) }}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Yakin ingin menghapus data ini?')">Delete</button>
                                    </form>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="text-center">Data Kosong</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            {{--  penerapan --}}
            <p>
                Kita lanjutkan dalam contoh penerapan inheritance, polimorphism juga menerapkan SOLID principles dalam
                laravel</p>
            <div>
                <h5>Enkapsulasi (Encapsulation):</h5>

                <ul>
                    <li>
                        <b>Deskripsi:</b> Enkapsulasi melibatkan pembungkusan data (variabel) dan metode (fungsi) yang
                        beroperasi
                        pada data
                        ke dalam satu unit yang disebut objek.
                    </li>
                    <li>
                        <b>Mengapa Penting:</b>
                        <br />
                        <b>Keamanan Data:</b> Enkapsulasi membantu melindungi data dengan membatasi akses langsung ke
                        variabel,
                        yang dapat
                        mencegah modifikasi atau manipulasi yang tidak sah.
                    </li>
                    <li>
                        <b>Abstraksi:</b> Menggunakan enkapsulasi memungkinkan pembuat kelas untuk menyembunyikan detail
                        implementasi
                        internal dari pengguna objek. Ini membuat objek dapat digunakan tanpa perlu mengetahui detail
                        bagaimana
                        objek tersebut bekerja di dalamnya.
                    </li>
                </ul>

                <h5>Warisan (Inheritance):</h5>
                <ul>
                    <li>
                        <b>Deskripsi:</b> Warisan memungkinkan suatu kelas untuk mewarisi properti (variabel) dan metode
                        (fungsi)
                        dari
                        kelas lain, yang disebut kelas induk atau superclass.
                    </li>
                    <li>
                        <b>Mengapa Penting:</b>
                        Penggunaan Kembali Kode: Dengan menggunakan warisan, Anda dapat menggunakan dan memperluas
                        fungsionalitas
                        yang sudah ada tanpa menulis ulang kode. Ini mempromosikan penggunaan kembali kode dan membuat
                        pengembangan
                        lebih efisien.
                    </li>
                    <li>
                        Pengelolaan dan Struktur Kode: Warisan membantu dalam pengelolaan dan struktur kode dengan
                        memungkinkan
                        pembagian fungsionalitas ke dalam hierarki kelas yang logis.
                    </li>
                </ul>
                <h5>Polimorfisme (Polymorphism):</h5>

                <ul>
                    <li>
                        <b>Deskripsi:</b> Polimorfisme memungkinkan objek untuk merespons pada metode-metode yang sama
                        dengan cara
                        yang
                        berbeda. Ini dapat dicapai melalui overloading dan overriding.
                    </li>
                    <li>
                        <b>Mengapa Penting:</b>
                        <br />
                        <b>Fleksibilitas:</b> Polimorfisme meningkatkan fleksibilitas dalam desain dan pengembangan. Objek
                        dapat
                        dianggap
                        sebagai objek dari kelas induk, yang memungkinkan kelas anak untuk digunakan secara transparan.
                    </li>
                    <li>
                        <b>Code Readability:</b> Polimorfisme meningkatkan kejelasan kode dengan memungkinkan penggunaan
                        metode
                        yang sama
                        dengan nama yang sama pada berbagai kelas, meskipun perilaku sebenarnya dapat bervariasi.
                    </li>
                </ul>
            </div>

            <p>*Yang Pertama aku akan bahas Enkapsulasi</p>
            <h5>Enkapsulasi:</h5>
            <p>
                Mari kita tambahkan contoh Enkapsulasi melibatkan pembungkusan data (variabel) dan metode
                (fungsi) yang beroperasi pada data ke dalam satu unit yang disebut objek, bisa di lihat pada garis warna
                merah.
            </p>
            <div class="d-flex align-items-center gap-2">
                @foreach ($secArticle as $item)
                    <div class="card" style="width: 18rem;">
                        <img src="/foods.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h6 class="card-title line-clamp">{{ $item->title }}</h6>
                            <p class="card-text text-muted line-clamp-3">
                                {{ $item->description }}
                            </p>
                            <div class="border border-2 border-danger">
                                <small style="font-style: italic">
                                    {{ $item->full_info }}
                                </small>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
            <div class="mt-4">
                <p>*Yang Kedua aku akan bahas Warisan (Inheritance)</p>
                <h5>Warisan (Inheritance):</h5>
                <p>
                    Deskripsi: Warisan memungkinkan suatu kelas untuk mewarisi properti (variabel) dan metode (fungsi) dari
                    kelas lain, yang disebut kelas induk atau superclass. bisa di lihat pada garis warna biru.
                </p>
                <div class="d-flex align-items-center gap-2">
                    @foreach ($inheArticle as $item)
                        <div class="card" style="width: 18rem;">
                            <img src="/foods.jpg" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h6 class="card-title line-clamp">{{ $item->title }}</h6>
                                <p class="card-text text-muted line-clamp-3">
                                    {{ $item->description }}
                                </p>
                                <div class="border border-2 border-primary">
                                    <small style="font-style: italic">
                                        {{ $item->blog_info }}
                                    </small>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="mt-4">
                <p>*Yang Ketiga aku akan bahas Polimorfisme (Polymorphism)</p>
                <h5>Polimorfisme (Polymorphism):</h5>
                <p>
                    Mari saya jelaskan lebih rinci tentang konsep polimorfisme dalam konteks Laravel.

                <ul>
                    <li>
                        Dalam konteks Laravel, polimorfisme sering digunakan untuk mengelola hubungan satu tabel dengan
                        banyak
                        model (entitas) lain. Dengan kata lain, kita dapat menggunakan satu tabel untuk menyimpan hubungan
                        banyak jenis objek tanpa perlu membuat tabel terpisah untuk setiap jenis objek tersebut.
                    </li>
                    <li>
                        Dalam contoh ini, kita ingin menyimpan gambar untuk buku dan mungkin jenis objek lainnya di masa
                        depan,
                        tanpa membuat tabel gambar terpisah untuk setiap jenis objek. Kita dapat menggunakan polimorfisme
                        untuk
                        mencapai hal ini.
                    </li>
                </ul>
                Sekarang kita dapat menyimpan komentar untuk artikel dan posting blog tanpa perlu membuat tabel komentar
                terpisah untuk setiap jenis objek.

                Dengan cara ini, kita menggabungkan konsep Enkapsulasi dengan aksesors dan mutators, Warisan dengan membuat
                kelas turunan, dan Polimorfisme dengan menggunakan hubungan polimorfik untuk mengatasi kebutuhan aplikasi
                dengan cara yang bersifat umum dan mudah diperluas.
                </p>
                <p>
                    Jika ingin melihat contohnya klik salah satu artikel dibawah ini, dan lihat pada bagian komentar.
                    Atau kamu juga bisa langsung berkomentar pada artikel tersebut.
                </p>
                <div class="d-flex align-items-center gap-2">
                    @foreach ($commArticle as $item)
                        <div class="card" style="width: 18rem;">
                            <a href="{{ route('articles.show', $item) }}"><img src="/foods.jpg" class="card-img-top"
                                    alt="..."></a>
                            <div class="card-body">
                                <h6 class="card-title line-clamp">{{ $item->title }}</h6>
                                <p class="card-text text-muted line-clamp-3">
                                    {{ $item->description }}
                                </p>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection